# ----------- GLOBAL CONFIGURATION -----------
# Communication channels
USE_SERIAL = False
USE_BLUETOOTH = False
USE_WIFI = False

# Hardware pins
PIR_SENSOR_PIN = 34
SERVO_PIN = 18

# Waste types and servo positions
WASTE_TYPES = ["PLASTIC", "PAPER", "GLASS", "METAL", "ORGANIC", "SPECIAL"]
SERVO_POSITIONS = [0, 30, 60, 90, 120, 150]
NEUTRAL_POSITION = 90  # Servo neutral position

# Network settings - STATIC IP for ESP32
ESP_IP = "192.168.1.100"  # Fixed IP of ESP32
ESP_SUBNET = "255.255.255.0"
ESP_GATEWAY = "192.168.1.1"
PC_IP_ADDRESS = "192.168.1.50"  # PC IP
UDP_PORT = 12345  # Communication port

# Wi-Fi credentials
WIFI_SSID = "YOUR_NETWORK_NAME"
WIFI_PASSWORD = "YOUR_PASSWORD"

# Timeouts and delays
MOVEMENT_TIMEOUT_MS = 10000       # 10 seconds
SERVO_MOVEMENT_DELAY = 0.5        # 500ms
WASTE_PROCESSING_DELAY = 2        # 2 seconds
SERIAL_READ_TIMEOUT = 100         # 100ms for serial check
STATUS_REPORT_INTERVAL = 30000    # 30 seconds
COMMUNICATION_TIMEOUT_MS = 5000   # 5 seconds for communication timeout
WIFI_CONNECTION_TIMEOUT_MS = 15000  # 15 seconds for Wi-Fi connection

# System states
NO_TYPE_SELECTED = -1
SYSTEM_READY = "READY"
SYSTEM_ERROR = "ERROR"

# Communication channels
CHANNEL_SERIAL = "SERIAL"
CHANNEL_UDP = "UDP"
CHANNEL_NONE = "NONE"

# System commands
CMD_SET_TYPE = "SET_TYPE:"
CMD_TYPE = "TYPE:"
CMD_STATUS = "STATUS"
CMD_GET_STATUS = "GET_STATUS"
CMD_HELP = "HELP"
CMD_SHUTDOWN = "SHUTDOWN"
CMD_RESTART = "RESTART"
CMD_RESET = "RESET"
CMD_CANCEL = "CANCEL"

# System messages
MSG_MOVEMENT_DETECTED = "MOVEMENT_DETECTED"
MSG_TYPE_SELECTED = "TYPE_SELECTED"
MSG_TYPE_DEFINED = "TYPE_DEFINED"
MSG_DISPOSAL_STARTED = "DISPOSAL_STARTED"
MSG_DISPOSAL_COMPLETED = "DISPOSAL_COMPLETED"
MSG_DISPOSAL_CANCELLED = "DISPOSAL_CANCELLED"
MSG_ERROR = "ERROR"
MSG_STATUS = "STATUS"
MSG_HELP = "HELP"
MSG_SYSTEM_STARTED = "SYSTEM_STARTED"
MSG_SYSTEM_RESTARTING = "SYSTEM_RESTARTING"
MSG_SYSTEM_RESET = "SYSTEM_RESET"
MSG_SERVO_INITIALIZED = "SERVO_INITIALIZED"
MSG_SERVO_MOVING = "SERVO_MOVING"
MSG_SERVO_POSITIONED = "SERVO_POSITIONED"
MSG_WAITING_DISPOSAL = "WAITING_FOR_DISPOSAL"
MSG_TIMEOUT = "TIMEOUT"

# Message prefixes
PREFIX_CANAL = "CHANNEL:"
PREFIX_TIPO = "TYPE:"
PREFIX_ANGULO = "ANGLE:"
PREFIX_NOME = "NAME:"

# Servo duty cycle values
SERVO_DUTY_MIN = 40
SERVO_DUTY_MAX = 155
SERVO_DUTY_RANGE = SERVO_DUTY_MAX - SERVO_DUTY_MIN
SERVO_FREQUENCY = 50

# Buffer sizes
UDP_BUFFER_SIZE = 1024
SERIAL_BUFFER_SIZE = 128

# Processing states
PROCESSING_ACTIVE = True
PROCESSING_INACTIVE = False